In [1]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
data_files = list((BASE_DIR / "data").glob("*.csv"))

print("Dataset files found:")
for file in data_files:
    print(file.name)

Dataset files found:
Daily Household Transactions.csv

In [2]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
file_path = BASE_DIR / "data" / "Daily Household Transactions.csv"

df = pd.read_csv(file_path)

print("Rows and columns:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

Rows and columns: (2461, 8)

Column names:
['Date', 'Mode', 'Category', 'Subcategory', 'Note', 'Amount', 'Income/Expense', 'Currency']

In [3]:
print("First 5 rows:")
display(df.head())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

First 5 rows:

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

Data types:
Date               object
Mode               object
Category           object
Subcategory        object
Note               object
Amount            float64
Income/Expense     object
Currency           object
dtype: object

Missing values:
Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

Duplicate rows:
9

In [4]:
print("Rows with missing Subcategory or Note:")
display(df[df["Subcategory"].isna() | df["Note"].isna()].head(10))

print("\nDuplicate rows:")
display(df[df.duplicated(keep=False)].sort_values(list(df.columns)).head(20))

Rows with missing Subcategory or Note:

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
8,13/09/2018 21:01:47,Credit Card,Other,NaN,HBR 2 Months subscription,83.0,Expense,INR
10,13/09/2018,Saving Bank account 1,Small Cap fund 2,NaN,NaN,5000.0,Transfer-Out,INR
11,13/09/2018,Saving Bank account 1,Small cap fund 1,NaN,NaN,5000.0,Transfer-Out,INR
14,11/9/2018,Saving Bank account 1,Other,NaN,From Family,3500.0,Income,INR
17,8/9/2018,Cash,Family,Pocket money,NaN,40.0,Expense,INR
19,7/9/2018,Saving Bank account 1,Equity Mutual Fund E,NaN,NaN,1000.0,Transfer-Out,INR
27,3/9/2018,Cash,Family,Pocket money,NaN,2000.0,Expense,INR
28,1/9/2018,Saving Bank account 1,Public Provident Fund,NaN,NaN,12500.0,Transfer-Out,INR
29,1/9/2018,Equity Mutual Fund B,Saving Bank account 1,NaN,NaN,2000.0,Transfer-Out,INR
30,31/08/2018 15:12:20,Cash,Family,Pocket money,NaN,1000.0,Expense,INR

Duplicate rows:

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
921,1/10/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
922,1/10/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
867,1/11/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
868,1/11/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
767,1/12/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
768,1/12/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1209,1/7/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1210,1/7/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1108,1/8/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1109,1/8/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1006,1/9/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1007,1/9/2017,Saving Bank account 1,Recurring Deposit,NaN,NaN,1000.0,Transfer-Out,INR
1853,10/10/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1854,10/10/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1815,10/11/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1816,10/11/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1360,12/5/2017,Cash,Food,Tea,NaN,10.0,Expense,INR
1362,12/5/2017,Cash,Food,Tea,NaN,10.0,Expense,INR

In [5]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))
print("Duplicate rows remaining:", df.duplicated().sum())

Rows after removing duplicates: 2452
Duplicate rows remaining: 0

In [6]:
print("Current number of rows:", df.shape[0])
print("Current number of columns:", df.shape[1])

Current number of rows: 2452
Current number of columns: 8

In [7]:
df["Subcategory"] = df["Subcategory"].fillna("Unknown")
df["Note"] = df["Note"].fillna("Unknown")

print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
Date              0
Mode              0
Category          0
Subcategory       0
Note              0
Amount            0
Income/Expense    0
Currency          0
dtype: int64

In [8]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")

print("Date data type:", df["Date"].dtype)
print("Invalid dates:", df["Date"].isna().sum())
print("\nDate range:")
print("Start:", df["Date"].min())
print("End:", df["Date"].max())

Date data type: datetime64[ns]
Invalid dates: 1149

Date range:
Start: 2015-01-13 18:52:47
End: 2018-09-20 12:04:08

In [9]:
invalid_dates = df[df["Date"].isna()]

print("Number of invalid dates:", len(invalid_dates))
print("\nInvalid date rows:")
display(invalid_dates.head(20))

Number of invalid dates: 1149

Invalid date rows:

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
2,NaT,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
10,NaT,Saving Bank account 1,Small Cap fund 2,Unknown,Unknown,5000.0,Transfer-Out,INR
11,NaT,Saving Bank account 1,Small cap fund 1,Unknown,Unknown,5000.0,Transfer-Out,INR
12,NaT,Credit Card,subscription,Mobile Service Provider,Data booster pack,667.0,Expense,INR
13,NaT,Saving Bank account 1,Food,Lunch,Home Food Delivery,650.0,Expense,INR
14,NaT,Saving Bank account 1,Other,Unknown,From Family,3500.0,Income,INR
15,NaT,Cash,Food,Milk,Half lit milk,36.0,Expense,INR
16,NaT,Cash,Food,Milk,Half lit milk,36.0,Expense,INR
17,NaT,Cash,Family,Pocket money,Unknown,40.0,Expense,INR
18,NaT,Cash,Food,Milk,Half lit milk,37.0,Expense,INR
19,NaT,Saving Bank account 1,Equity Mutual Fund E,Unknown,Unknown,1000.0,Transfer-Out,INR
20,NaT,Cash,Food,snacks,Amul butter,55.0,Expense,INR
21,NaT,Cash,Apparel,Laundry,11 clothes ironing,77.0,Expense,INR
22,NaT,Cash,Food,snacks,Chinese Bhel,30.0,Expense,INR
23,NaT,Cash,Food,snacks,Shev Puri,40.0,Expense,INR
24,NaT,Cash,Food,snacks,2 kachori,24.0,Expense,INR
25,NaT,Saving Bank account 1,Food,Milk,Half lit milk,36.0,Expense,INR
26,NaT,Saving Bank account 1,Food,breakfast,Bread,18.0,Expense,INR
27,NaT,Cash,Family,Pocket money,Unknown,2000.0,Expense,INR
28,NaT,Saving Bank account 1,Public Provident Fund,Unknown,Unknown,12500.0,Transfer-Out,INR

In [10]:
raw_df = pd.read_csv(file_path)

print("Original rows:", len(raw_df))
print("\nSample Date values:")
print(raw_df["Date"].head(20).to_string(index=False))

Original rows: 2461

Sample Date values:
20/09/2018 12:04:08
20/09/2018 12:03:15
         19/09/2018
17/09/2018 23:41:17
16/09/2018 17:15:08
15/09/2018 06:34:17
14/09/2018 05:39:17
13/09/2018 21:35:15
13/09/2018 21:01:47
13/09/2018 21:01:32
         13/09/2018
         13/09/2018
          12/9/2018
          11/9/2018
          11/9/2018
          11/9/2018
          10/9/2018
           8/9/2018
           7/9/2018
           7/9/2018

In [12]:
df["Date"] = pd.to_datetime(
    raw_df["Date"],
    dayfirst=True,
    format="mixed",
    errors="coerce"
)

print("Invalid dates:", df["Date"].isna().sum())
print("Date data type:", df["Date"].dtype)
print("Start date:", df["Date"].min())
print("End date:", df["Date"].max())

Invalid dates: 0
Date data type: datetime64[ns]
Start date: 2015-01-01 00:00:00
End date: 2018-09-20 12:04:08

In [13]:
print("Mode values:")
print(df["Mode"].value_counts())

print("\nCategory values:")
print(df["Category"].value_counts())

print("\nIncome/Expense values:")
print(df["Income/Expense"].value_counts())

print("\nCurrency values:")
print(df["Currency"].value_counts())

Mode values:
Mode
Saving Bank account 1    1215
Cash                     1045
Credit Card               162
Equity Mutual Fund B       11
Share Market Trading        5
Saving Bank account 2       5
Recurring Deposit           3
Debit Card                  2
Equity Mutual Fund C        1
Equity Mutual Fund A        1
Equity Mutual Fund D        1
Fixed Deposit               1
Name: count, dtype: int64

Category values:
Category
Food                         906
Transportation               307
Household                    176
subscription                 143
Other                        126
Investment                   101
Health                        94
Family                        71
Apparel                       47
Salary                        43
Money transfer                43
Recurring Deposit             41
Gift                          30
Public Provident Fund         29
Equity Mutual Fund E          22
Beauty                        22
Gpay Reward                   21
Education                     18
Saving Bank account 1         17
maid                          17
Festivals                     16
Equity Mutual Fund A          14
Equity Mutual Fund F          13
Dividend earned on Shares     12
Interest                      12
Culture                       11
Small Cap fund 2              10
Small cap fund 1              10
Share Market                   8
Life Insurance                 7
Maturity amount                7
Petty cash                     6
Equity Mutual Fund C           6
Bonus                          6
Tourism                        5
Rent                           4
Cook                           4
Grooming                       4
Saving Bank account 2          3
water (jar /tanker)            3
Self-development               2
Tax refund                     2
garbage disposal               2
Documents                      2
Amazon pay cashback            2
scrap                          2
Fixed Deposit                  2
Social Life                    1
Equity Mutual Fund D           1
Equity Mutual Fund B           1
Name: count, dtype: int64

Income/Expense values:
Income/Expense
Expense         2173
Transfer-Out     154
Income           125
Name: count, dtype: int64

Currency values:
Currency
INR    2452
Name: count, dtype: int64

In [14]:
print("All Category values:")
print(sorted(df["Category"].unique()))

print("\nAll Income/Expense values:")
print(sorted(df["Income/Expense"].unique()))

print("\nAll Subcategory values:")
print(sorted(df["Subcategory"].unique()))

All Category values:
['Amazon pay cashback', 'Apparel', 'Beauty', 'Bonus', 'Cook', 'Culture', 'Dividend earned on Shares', 'Documents', 'Education', 'Equity Mutual Fund A', 'Equity Mutual Fund B', 'Equity Mutual Fund C', 'Equity Mutual Fund D', 'Equity Mutual Fund E', 'Equity Mutual Fund F', 'Family', 'Festivals', 'Fixed Deposit', 'Food', 'Gift', 'Gpay Reward', 'Grooming', 'Health', 'Household', 'Interest', 'Investment', 'Life Insurance', 'Maturity amount', 'Money transfer', 'Other', 'Petty cash', 'Public Provident Fund', 'Recurring Deposit', 'Rent', 'Salary', 'Saving Bank account 1', 'Saving Bank account 2', 'Self-development', 'Share Market', 'Small Cap fund 2', 'Small cap fund 1', 'Social Life', 'Tax refund', 'Tourism', 'Transportation', 'garbage disposal', 'maid', 'scrap', 'subscription', 'water (jar /tanker)']

All Income/Expense values:
['Expense', 'Income', 'Transfer-Out']

All Subcategory values:
['Accessories', 'Amazon Prime', 'Appliances', 'Audible', 'Bike', 'Biscuits', 'Books', 'Bread', 'Bus', 'Cable TV', 'Clothing', 'Courier', 'Dinner', 'Diwali', 'Eating out', 'Edtech Course', 'Eggs', 'Entry Fees', 'Footwear', 'Furniture', 'Ganesh Pujan', 'Grocery', 'Hardware', 'Health', 'Holi', 'Home', 'Hospital', 'Hotstar', 'Ice cream', 'Kindle unlimited', 'Kirana', 'Kitchen', 'LIC', 'Lab Tests', 'Laundry', 'Leisure', 'Lunch', 'Mahanagar Gas', 'Makeup', 'Medicine', 'Milk', 'Mobile Service Provider', 'Movie', 'Mutual fund', 'Navratri', 'Netflix', 'Newspaper', 'OTT Platform', 'Onions', 'Petrol', 'Pocket money', 'Potato', 'Public Provident Fund', 'RD', 'Rajgira ladu', 'Rakshabandhan', 'Saloon', 'School supplies', 'Stationary', 'Sweets', 'Tata Sky', 'Taxi', 'Tea', 'Toiletries', 'Train', 'Travels', 'Trip', 'Unknown', 'Updation', 'Water', 'Wifi Internet Service', 'auto', 'beverage', 'breakfast', 'chocolate', 'clothes', 'curd', 'exam fee', 'flour mill', 'fruits', 'gadgets', 'gift', 'grooming', 'home decor', 'makeup', 'medicine', 'misc', 'ropeway', 'snacks', 'train', 'vegetables']

In [15]:
text_columns = ["Mode", "Category", "Subcategory", "Note", "Income/Expense", "Currency"]

for column in text_columns:
    spaces = (df[column].astype(str) != df[column].astype(str).str.strip()).sum()
    print(column, "values with extra spaces:", spaces)

Mode values with extra spaces: 0
Category values with extra spaces: 0
Subcategory values with extra spaces: 0
Note values with extra spaces: 161
Income/Expense values with extra spaces: 0
Currency values with extra spaces: 0

In [16]:
note_spaces = df[df["Note"].astype(str) != df["Note"].astype(str).str.strip()]

print("Number of affected notes:", len(note_spaces))
display(note_spaces[["Note"]].head(20))

Number of affected notes: 161

                Note
33   From workplace
105  From workplace
116          2 INOX
184           2 PVR
189       milk 1lit
195  From workplace
227       milk 1lit
250  From workplace
286       milk 1lit
295       milk 1lit
301       milk 1lit
306       milk 1lit
309       milk 1lit
320       milk 1lit
323  From workplace
328       milk 1lit
336       milk 1lit
342       milk 1lit
343       milk 1lit
359       milk 1lit

In [17]:
for column in text_columns:
    df[column] = df[column].astype(str).str.strip()

print("Extra spaces remaining:")
for column in text_columns:
    spaces = (df[column] != df[column].str.strip()).sum()
    print(column, spaces)

Extra spaces remaining:
Mode 0
Category 0
Subcategory 0
Note 0
Income/Expense 0
Currency 0

In [18]:
print("Amount data type:", df["Amount"].dtype)
print("Missing amounts:", df["Amount"].isna().sum())
print("Negative amounts:", (df["Amount"] < 0).sum())
print("Zero amounts:", (df["Amount"] == 0).sum())

print("\nAmount statistics:")
print(df["Amount"].describe())

Amount data type: float64
Missing amounts: 0
Negative amounts: 0
Zero amounts: 0

Amount statistics:
count      2452.000000
mean       2757.976664
std       12542.057491
min           2.000000
25%          35.000000
50%         100.000000
75%         784.500000
max      250000.000000
Name: Amount, dtype: float64

In [19]:
print("Income/Expense values:")
print(df["Income/Expense"].value_counts())

print("\nCurrency values:")
print(df["Currency"].value_counts())

print("\nAmount by transaction type:")
print(df.groupby("Income/Expense")["Amount"].agg(["count", "sum", "mean"]))

Income/Expense values:
Income/Expense
Expense         2173
Transfer-Out     154
Income           125
Name: count, dtype: int64

Currency values:
Currency
INR    2452
Name: count, dtype: int64

Amount by transaction type:
                count         sum          mean
Income/Expense
Expense          2173  1955380.53    899.852982
Income            125  3042397.35  24339.178800
Transfer-Out      154  1764780.90  11459.616234

In [20]:
category_check = df["Category"].dropna().astype(str)

category_groups = category_check.groupby(category_check.str.lower()).unique()

print("Categories with different capitalization:")
for key, values in category_groups.items():
    if len(values) > 1:
        print(values.tolist())

Categories with different capitalization:

In [21]:
print("Final dataset shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Invalid dates:", df["Date"].isna().sum())
print("Negative amounts:", (df["Amount"] < 0).sum())
print("Zero amounts:", (df["Amount"] == 0).sum())
print("Currencies:", df["Currency"].unique())

Final dataset shape: (2452, 8)
Missing values: 0
Duplicate rows: 0
Invalid dates: 0
Negative amounts: 0
Zero amounts: 0
Currencies: ['INR']

In [22]:
cleaned_file_path = BASE_DIR / "data" / "cleaned_transactions.csv"

df.to_csv(cleaned_file_path, index=False)

print("Cleaned dataset saved successfully.")
print("File:", cleaned_file_path)

Cleaned dataset saved successfully.
File: s:\5th sem\EDP\Personal-Finance-Assistant-New\data\cleaned_transactions.csv

In [23]:
X = df["Note"]
y = df["Category"]

print("Number of transactions:", len(df))
print("Number of categories:", y.nunique())
print("\nTransactions per category:")
print(y.value_counts())

Number of transactions: 2452
Number of categories: 50

Transactions per category:
Category
Food                         906
Transportation               307
Household                    176
subscription                 143
Other                        126
Investment                   101
Health                        94
Family                        71
Apparel                       47
Salary                        43
Money transfer                43
Recurring Deposit             41
Gift                          30
Public Provident Fund         29
Equity Mutual Fund E          22
Beauty                        22
Gpay Reward                   21
Education                     18
Saving Bank account 1         17
maid                          17
Festivals                     16
Equity Mutual Fund A          14
Equity Mutual Fund F          13
Dividend earned on Shares     12
Interest                      12
Culture                       11
Small Cap fund 2              10
Small cap fund 1              10
Share Market                   8
Life Insurance                 7
Maturity amount                7
Petty cash                     6
Equity Mutual Fund C           6
Bonus                          6
Tourism                        5
Rent                           4
Cook                           4
Grooming                       4
Saving Bank account 2          3
water (jar /tanker)            3
Self-development               2
Tax refund                     2
garbage disposal               2
Documents                      2
Amazon pay cashback            2
scrap                          2
Fixed Deposit                  2
Social Life                    1
Equity Mutual Fund D           1
Equity Mutual Fund B           1
Name: count, dtype: int64

In [24]:
category_counts = y.value_counts()

rare_categories = category_counts[category_counts < 5]

print("Number of rare categories:", len(rare_categories))
print("\nRare categories:")
print(rare_categories)

Number of rare categories: 15

Rare categories:
Category
Rent                     4
Cook                     4
Grooming                 4
Saving Bank account 2    3
water (jar /tanker)      3
Self-development         2
Tax refund               2
garbage disposal         2
Documents                2
Amazon pay cashback      2
scrap                    2
Fixed Deposit            2
Social Life              1
Equity Mutual Fund D     1
Equity Mutual Fund B     1
Name: count, dtype: int64

In [25]:
category_counts = y.value_counts()

y_model = y.where(y.map(category_counts) >= 5, "Other")

print("Original categories:", y.nunique())
print("ML categories:", y_model.nunique())
print("\nML category distribution:")
print(y_model.value_counts())

Original categories: 50
ML categories: 35

ML category distribution:
Category
Food                         906
Transportation               307
Household                    176
Other                        161
subscription                 143
Investment                   101
Health                        94
Family                        71
Apparel                       47
Salary                        43
Money transfer                43
Recurring Deposit             41
Gift                          30
Public Provident Fund         29
Equity Mutual Fund E          22
Beauty                        22
Gpay Reward                   21
Education                     18
Saving Bank account 1         17
maid                          17
Festivals                     16
Equity Mutual Fund A          14
Equity Mutual Fund F          13
Dividend earned on Shares     12
Interest                      12
Culture                       11
Small cap fund 1              10
Small Cap fund 2              10
Share Market                   8
Life Insurance                 7
Maturity amount                7
Equity Mutual Fund C           6
Petty cash                     6
Bonus                          6
Tourism                        5
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_model,
    test_size=0.2,
    random_state=42,
    stratify=y_model
)

print("Training transactions:", len(X_train))
print("Testing transactions:", len(X_test))
print("Training categories:", y_train.nunique())
print("Testing categories:", y_test.nunique())

Training transactions: 1961
Testing transactions: 491
Training categories: 35
Testing categories: 35

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2)
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)
print("Number of features:", len(vectorizer.get_feature_names_out()))

Training TF-IDF shape: (1961, 2486)
Testing TF-IDF shape: (491, 2486)
Number of features: 2486

In [28]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

print("Model training completed successfully.")

Model training completed successfully.

In [29]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

Model Accuracy: 0.6069246435845214

Classification Report:
                           precision    recall  f1-score   support

                  Apparel       1.00      0.50      0.67        10
                   Beauty       0.50      0.20      0.29         5
                    Bonus       0.00      0.00      0.00         1
                  Culture       0.00      0.00      0.00         2
Dividend earned on Shares       0.00      0.00      0.00         2
                Education       0.00      0.00      0.00         4
     Equity Mutual Fund A       0.00      0.00      0.00         3
     Equity Mutual Fund C       0.00      0.00      0.00         1
     Equity Mutual Fund E       0.00      0.00      0.00         4
     Equity Mutual Fund F       0.00      0.00      0.00         3
                   Family       0.00      0.00      0.00        14
                Festivals       0.00      0.00      0.00         3
                     Food       0.49      1.00      0.66       182
                     Gift       1.00      0.17      0.29         6
              Gpay Reward       0.00      0.00      0.00         4
                   Health       1.00      0.21      0.35        19
                Household       1.00      0.20      0.33        35
                 Interest       0.00      0.00      0.00         2
               Investment       1.00      0.55      0.71        20
           Life Insurance       0.00      0.00      0.00         1
          Maturity amount       0.00      0.00      0.00         1
           Money transfer       0.00      0.00      0.00         9
                    Other       0.83      0.16      0.26        32
               Petty cash       0.00      0.00      0.00         1
    Public Provident Fund       0.00      0.00      0.00         6
        Recurring Deposit       0.00      0.00      0.00         8
                   Salary       1.00      1.00      1.00         9
    Saving Bank account 1       0.00      0.00      0.00         3
             Share Market       0.00      0.00      0.00         2
         Small Cap fund 2       0.00      0.00      0.00         2
         Small cap fund 1       0.00      0.00      0.00         2
                  Tourism       0.00      0.00      0.00         1
           Transportation       1.00      0.95      0.98        62
                     maid       0.00      0.00      0.00         3
             subscription       0.93      0.48      0.64        29

                 accuracy                           0.61       491
                macro avg       0.28      0.15      0.18       491
             weighted avg       0.62      0.61      0.53       491

In [30]:
X_combined = (
    df["Note"].astype(str) + " " +
    df["Subcategory"].astype(str) + " " +
    df["Mode"].astype(str)
)

X_train, X_test, y_train, y_test = train_test_split(
    X_combined,
    y_model,
    test_size=0.2,
    random_state=42,
    stratify=y_model
)

print("Training transactions:", len(X_train))
print("Testing transactions:", len(X_test))
print("Training categories:", y_train.nunique())
print("Testing categories:", y_test.nunique())

Training transactions: 1961
Testing transactions: 491
Training categories: 35
Testing categories: 35

In [31]:
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    min_df=2
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)
print("Number of features:", len(vectorizer.get_feature_names_out()))

Training TF-IDF shape: (1961, 1211)
Testing TF-IDF shape: (491, 1211)
Number of features: 1211

In [32]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

print("Improved model training completed successfully.")

Improved model training completed successfully.

In [33]:
y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)

print("Improved Model Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

Improved Model Accuracy: 0.7861507128309573

Classification Report:
                           precision    recall  f1-score   support

                  Apparel       1.00      0.50      0.67        10
                   Beauty       1.00      0.80      0.89         5
                    Bonus       0.00      0.00      0.00         1
                  Culture       0.00      0.00      0.00         2
Dividend earned on Shares       0.00      0.00      0.00         2
                Education       0.00      0.00      0.00         4
     Equity Mutual Fund A       0.00      0.00      0.00         3
     Equity Mutual Fund C       0.00      0.00      0.00         1
     Equity Mutual Fund E       0.00      0.00      0.00         4
     Equity Mutual Fund F       0.00      0.00      0.00         3
                   Family       1.00      0.79      0.88        14
                Festivals       0.00      0.00      0.00         3
                     Food       0.78      1.00      0.88       182
                     Gift       1.00      0.17      0.29         6
              Gpay Reward       0.00      0.00      0.00         4
                   Health       1.00      0.89      0.94        19
                Household       1.00      0.80      0.89        35
                 Interest       0.00      0.00      0.00         2
               Investment       0.83      1.00      0.91        20
           Life Insurance       0.00      0.00      0.00         1
          Maturity amount       0.00      0.00      0.00         1
           Money transfer       1.00      0.56      0.71         9
                    Other       0.25      0.50      0.33        32
               Petty cash       0.00      0.00      0.00         1
    Public Provident Fund       0.00      0.00      0.00         6
        Recurring Deposit       0.00      0.00      0.00         8
                   Salary       1.00      1.00      1.00         9
    Saving Bank account 1       0.00      0.00      0.00         3
             Share Market       0.00      0.00      0.00         2
         Small Cap fund 2       0.00      0.00      0.00         2
         Small cap fund 1       0.00      0.00      0.00         2
                  Tourism       0.00      0.00      0.00         1
           Transportation       1.00      1.00      1.00        62
                     maid       0.00      0.00      0.00         3
             subscription       0.96      0.90      0.93        29

                 accuracy                           0.79       491
                macro avg       0.34      0.28      0.29       491
             weighted avg       0.74      0.79      0.75       491

In [34]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC()
svm_model.fit(X_train_tfidf, y_train)

print("Linear SVM model training completed successfully.")

Linear SVM model training completed successfully.

In [35]:
svm_pred = svm_model.predict(X_test_tfidf)

svm_accuracy = accuracy_score(y_test, svm_pred)

print("Linear SVM Accuracy:", svm_accuracy)
print("\nClassification Report:")
print(classification_report(y_test, svm_pred, zero_division=0))

Linear SVM Accuracy: 0.8961303462321792

Classification Report:
                           precision    recall  f1-score   support

                  Apparel       1.00      1.00      1.00        10
                   Beauty       0.83      1.00      0.91         5
                    Bonus       0.50      1.00      0.67         1
                  Culture       1.00      1.00      1.00         2
Dividend earned on Shares       1.00      1.00      1.00         2
                Education       1.00      1.00      1.00         4
     Equity Mutual Fund A       0.00      0.00      0.00         3
     Equity Mutual Fund C       0.00      0.00      0.00         1
     Equity Mutual Fund E       0.00      0.00      0.00         4
     Equity Mutual Fund F       0.00      0.00      0.00         3
                   Family       1.00      1.00      1.00        14
                Festivals       1.00      1.00      1.00         3
                     Food       0.99      0.99      0.99       182
                     Gift       0.75      0.50      0.60         6
              Gpay Reward       0.00      0.00      0.00         4
                   Health       0.95      1.00      0.97        19
                Household       1.00      0.94      0.97        35
                 Interest       1.00      1.00      1.00         2
               Investment       1.00      1.00      1.00        20
           Life Insurance       0.00      0.00      0.00         1
          Maturity amount       0.00      0.00      0.00         1
           Money transfer       1.00      0.56      0.71         9
                    Other       0.84      0.66      0.74        32
               Petty cash       0.33      1.00      0.50         1
    Public Provident Fund       0.00      0.00      0.00         6
        Recurring Deposit       0.19      1.00      0.31         8
                   Salary       1.00      1.00      1.00         9
    Saving Bank account 1       0.75      1.00      0.86         3
             Share Market       0.00      0.00      0.00         2
         Small Cap fund 2       0.00      0.00      0.00         2
         Small cap fund 1       0.00      0.00      0.00         2
                  Tourism       1.00      1.00      1.00         1
           Transportation       1.00      1.00      1.00        62
                     maid       0.60      1.00      0.75         3
             subscription       0.97      1.00      0.98        29

                 accuracy                           0.90       491
                macro avg       0.59      0.65      0.60       491
             weighted avg       0.90      0.90      0.89       491

In [36]:
test_transactions = [
    "Uber ride to office",
    "Netflix monthly subscription",
    "Grocery shopping for vegetables",
    "Doctor consultation",
    "New clothes purchase",
    "Train ticket to Hyderabad"
]

test_features = vectorizer.transform(
    [text + " Unknown Cash" for text in test_transactions]
)

predictions = svm_model.predict(test_features)

for transaction, prediction in zip(test_transactions, predictions):
    print(transaction, "->", prediction)

Uber ride to office -> Other
Netflix monthly subscription -> Other
Grocery shopping for vegetables -> Food
Doctor consultation -> Other
New clothes purchase -> Other
Train ticket to Hyderabad -> Transportation

In [37]:
categories_to_check = ["Transportation", "subscription", "Health", "Apparel", "Food"]

for category in categories_to_check:
    print("\n", category)
    display(df[df["Category"] == category]["Note"].head(10))

 Transportation

0                             2 Place 5 to Place 0
6           Place 2 station to Permanent Residence
7                             2 Place 0 to Place 3
53     2 Place 2 to Place 3 : Sevagram express 3AC
54     2 Place 3 to Place 2 : Amritsar express 3AC
89                       Place 0 to Place 4 return
90                    Current Residence to Place 0
111           Decathlon Place A to Place A station
112                   Current Residence to Place 0
113                   2 Place 0 to Place A returns
Name: Note, dtype: object

 subscription

2                          1 month subscription
3                             Data booster pack
5      Permanent Residence - Tata Play recharge
12                            Data booster pack
60                         1 month subscription
64     Permanent Residence - Tata Play recharge
122      Current Residence - Tata Play recharge
161                                     Unknown
175      Current Residence - Tata Play recharge
230    Permanent Residence - Tata Play recharge
Name: Note, dtype: object

 Health

87             eyewear Glasses payment remaining
97                       eyewear Glasses advance
106    Glucose D(50) + flora bc (40)+cyra 20(10)
107                                      Unknown
132                            Cataract Medicine
133                            Cataract Medicine
144                            Cataract Medicine
155                                     eye drop
156                        Hospital consultation
169                                  Doctor Fees
Name: Note, dtype: object

 Apparel

21               11 clothes ironing
47               13 clothes ironing
71                8 clothes ironing
88                       For Family
101              13 clothes ironing
136              12 clothes ironing
187    undergarments pair of Jockey
188                 clothes ironing
203           Mast & Harbour Slides
210                           Purse
Name: Note, dtype: object

 Food

1     Idli medu Vada mix 2 plates
9                        1kg atta
13             Home Food Delivery
15                 Half lit  milk
16                 Half lit  milk
18                 Half lit  milk
20                    Amul butter
22                   Chinese Bhel
23                      Shev Puri
24                      2 kachori
Name: Note, dtype: object

In [38]:
note_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    min_df=2
)

X_note_train, X_note_test, y_note_train, y_note_test = train_test_split(
    df["Note"],
    y_model,
    test_size=0.2,
    random_state=42,
    stratify=y_model
)

X_note_train_tfidf = note_vectorizer.fit_transform(X_note_train)
X_note_test_tfidf = note_vectorizer.transform(X_note_test)

note_svm_model = LinearSVC()
note_svm_model.fit(X_note_train_tfidf, y_note_train)

note_svm_pred = note_svm_model.predict(X_note_test_tfidf)
note_svm_accuracy = accuracy_score(y_note_test, note_svm_pred)

print("Note-Only SVM Accuracy:", note_svm_accuracy)

Note-Only SVM Accuracy: 0.6680244399185336

In [39]:
def categorize_transaction(description):
    text = description.lower()

    keyword_rules = {
        "Transportation": ["uber", "ola", "taxi", "train", "bus", "metro", "flight", "fuel", "petrol", "diesel"],
        "subscription": ["netflix", "spotify", "prime", "subscription", "recharge", "hotstar"],
        "Health": ["doctor", "hospital", "medicine", "pharmacy", "medical", "clinic"],
        "Apparel": ["clothes", "shirt", "dress", "shoes", "jeans", "apparel"],
        "Food": ["grocery", "vegetables", "restaurant", "food", "lunch", "dinner", "breakfast"],
        "Household": ["furniture", "cleaning", "household", "kitchen"]
    }

    for category, keywords in keyword_rules.items():
        if any(keyword in text for keyword in keywords):
            return category

    features = vectorizer.transform([description + " Unknown Cash"])
    return svm_model.predict(features)[0]

print(categorize_transaction("Uber ride to office"))
print(categorize_transaction("Netflix monthly subscription"))
print(categorize_transaction("Doctor consultation"))

Transportation
subscription
Health

In [40]:
test_transactions = [
    "Uber ride to airport",
    "Netflix monthly subscription",
    "Doctor consultation fee",
    "New shoes purchase",
    "Grocery shopping",
    "Electricity bill payment",
    "Train ticket",
    "Amazon shopping order",
    "Salary credited",
    "Movie ticket"
]

for transaction in test_transactions:
    print(transaction, "->", categorize_transaction(transaction))

Uber ride to airport -> Transportation
Netflix monthly subscription -> subscription
Doctor consultation fee -> Health
New shoes purchase -> Apparel
Grocery shopping -> Food
Electricity bill payment -> Household
Train ticket -> Transportation
Amazon shopping order -> Other
Salary credited -> Other
Movie ticket -> Culture

In [42]:
keyword_rules = {
    "Transportation": ["uber", "ola", "taxi", "train", "bus", "metro", "flight", "fuel", "petrol", "diesel"],
    "subscription": ["netflix", "spotify", "prime", "subscription", "recharge", "hotstar"],
    "Health": ["doctor", "hospital", "medicine", "pharmacy", "medical", "clinic"],
    "Apparel": ["clothes", "shirt", "dress", "shoes", "jeans", "apparel"],
    "Food": ["grocery", "vegetables", "restaurant", "food", "lunch", "dinner", "breakfast"],
    "Household": ["furniture", "cleaning", "household", "kitchen", "electricity", "water bill", "gas bill"],
    "Shopping": ["amazon", "shopping", "flipkart", "online order", "purchase"],
    "Income": ["salary", "credited", "income", "paycheck", "wages"]
}

In [43]:
def categorize_transaction(description):
    text = description.lower()

    keyword_rules = {
        "Transportation": ["uber", "ola", "taxi", "train", "bus", "metro", "flight", "fuel", "petrol", "diesel"],
        "subscription": ["netflix", "spotify", "prime", "subscription", "recharge", "hotstar"],
        "Health": ["doctor", "hospital", "medicine", "pharmacy", "medical", "clinic"],
        "Apparel": ["clothes", "shirt", "dress", "shoes", "jeans", "apparel"],
        "Food": ["grocery", "vegetables", "restaurant", "food", "lunch", "dinner", "breakfast"],
        "Household": ["furniture", "cleaning", "household", "kitchen", "electricity", "water bill", "gas bill"],
        "Shopping": ["amazon", "shopping", "flipkart", "online order", "purchase"],
        "Income": ["salary", "credited", "income", "paycheck", "wages"]
    }

    for category, keywords in keyword_rules.items():
        if any(keyword in text for keyword in keywords):
            return category

    features = vectorizer.transform([description + " Unknown Cash"])
    return svm_model.predict(features)[0]

In [44]:
test_transactions = [
    "Uber ride to airport",
    "Netflix monthly subscription",
    "Doctor consultation fee",
    "New shoes purchase",
    "Grocery shopping",
    "Electricity bill payment",
    "Train ticket",
    "Amazon shopping order",
    "Salary credited",
    "Movie ticket"
]

for transaction in test_transactions:
    print(transaction, "->", categorize_transaction(transaction))

Uber ride to airport -> Transportation
Netflix monthly subscription -> subscription
Doctor consultation fee -> Health
New shoes purchase -> Apparel
Grocery shopping -> Food
Electricity bill payment -> Household
Train ticket -> Transportation
Amazon shopping order -> Shopping
Salary credited -> Income
Movie ticket -> Culture

In [45]:
import joblib

model_path = BASE_DIR / "svm_category_model.pkl"
vectorizer_path = BASE_DIR / "tfidf_vectorizer.pkl"

joblib.dump(svm_model, model_path)
joblib.dump(vectorizer, vectorizer_path)

print("Model saved:", model_path)
print("Vectorizer saved:", vectorizer_path)

Model saved: s:\5th sem\EDP\Personal-Finance-Assistant-New\svm_category_model.pkl
Vectorizer saved: s:\5th sem\EDP\Personal-Finance-Assistant-New\tfidf_vectorizer.pkl

In [46]:
src_dir = BASE_DIR / "src"
src_dir.mkdir(exist_ok=True)

model_file = src_dir / "transaction_categorization.py"

code = '''
import joblib
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

model = joblib.load(BASE_DIR / "svm_category_model.pkl")
vectorizer = joblib.load(BASE_DIR / "tfidf_vectorizer.pkl")

def categorize_transaction(description):
    text = description.lower()

    keyword_rules = {
        "Transportation": ["uber", "ola", "taxi", "train", "bus", "metro", "flight", "fuel", "petrol", "diesel"],
        "subscription": ["netflix", "spotify", "prime", "subscription", "recharge", "hotstar"],
        "Health": ["doctor", "hospital", "medicine", "pharmacy", "medical", "clinic"],
        "Apparel": ["clothes", "shirt", "dress", "shoes", "jeans", "apparel"],
        "Food": ["grocery", "vegetables", "restaurant", "food", "lunch", "dinner", "breakfast"],
        "Household": ["furniture", "cleaning", "household", "kitchen", "electricity", "water bill", "gas bill"],
        "Shopping": ["amazon", "shopping", "flipkart", "online order", "purchase"],
        "Income": ["salary", "credited", "income", "paycheck", "wages"]
    }

    for category, keywords in keyword_rules.items():
        if any(keyword in text for keyword in keywords):
            return category

    features = vectorizer.transform([description + " Unknown Cash"])
    return model.predict(features)[0]
'''

model_file.write_text(code, encoding="utf-8")

print("Week 4 model file created successfully.")
print("File:", model_file)

Week 4 model file created successfully.
File: s:\5th sem\EDP\Personal-Finance-Assistant-New\src\transaction_categorization.py

In [47]:
import sys

sys.path.append(str(BASE_DIR / "src"))

from transaction_categorization import categorize_transaction

test_description = "Uber ride to office"

result = categorize_transaction(test_description)

print("Transaction:", test_description)
print("Predicted Category:", result)

Transaction: Uber ride to office
Predicted Category: Transportation